import React, { createContext, useContext, useState, useCallback } from 'react';

export type Language = 'en' | 'hi' | 'kn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.students': 'Students',
    'nav.canteens': 'Canteens',
    'nav.kitchen': 'Kitchen Queue',
    'nav.orders': 'Orders',
    'nav.menu': 'Menu',
    'nav.analytics': 'Analytics',
    'nav.reports': 'Reports',
    'nav.campus': 'Campus',
    'nav.staff': 'Staff & Roles',
    'nav.notifications': 'Announcements',
    'nav.ai_center': 'AI Center',
    'nav.settings': 'Settings',

    // Dashboard
    'dashboard.greeting.morning': 'Good morning',
    'dashboard.greeting.afternoon': 'Good afternoon',
    'dashboard.greeting.evening': 'Good evening',
    'dashboard.todays_orders': "Today's Orders",
    'dashboard.todays_revenue': "Today's Revenue",
    'dashboard.preparing': 'Preparing',
    'dashboard.ready': 'Ready',
    'dashboard.completed': 'Completed',
    'dashboard.active_canteens': 'Active Canteens',
    'dashboard.live_operations': 'Live Operations',
    'dashboard.realtime_pipeline': 'Real-time order pipeline',
    'dashboard.view_kitchen': 'View Kitchen',
    'dashboard.kitchen_queue': 'Kitchen Queue',
    'dashboard.orders_requiring_attention': 'Orders requiring attention',
    'dashboard.view_all': 'View All',
    'dashboard.no_active_orders': 'No active orders',
    'dashboard.orders_will_appear': 'Orders will appear here when students place them',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.manage_menu': 'Manage Menu',
    'dashboard.add_or_update': 'Add or update items',
    'dashboard.announcements': 'Announcements',
    'dashboard.broadcast_to_campus': 'Broadcast to campus',
    'dashboard.scan_pickup': 'Scan Pickup',
    'dashboard.qr_code_scanner': 'QR code scanner',
    'dashboard.reports': 'Reports',
    'dashboard.export_data': 'Export data & analytics',
    'dashboard.canteens': 'Canteens',
    'dashboard.total_orders': 'total orders',
    'dashboard.active_canteen_count': 'active canteens',
    'dashboard.orders_being_prepared': 'orders being prepared.',

    // Kitchen
    'kitchen.title': 'Kitchen Queue Display System',
    'kitchen.live': 'LIVE',
    'kitchen.subtitle': 'Supabase Realtime orders for the logged-in institution.',
    'kitchen.queue': 'Queue',
    'kitchen.incoming_queue': 'Incoming Queue',
    'kitchen.pending_accepted': 'Pending / Accepted',
    'kitchen.no_pending_orders': 'No pending orders.',
    'kitchen.preparing': 'Preparing',
    'kitchen.live_timer': 'Live Timer',
    'kitchen.no_orders_preparing': 'No orders preparing.',
    'kitchen.ready_counter': 'Ready Counter',
    'kitchen.ready': 'Ready',
    'kitchen.no_orders_ready': 'No orders ready.',
    'kitchen.completed': 'Completed',
    'kitchen.picked_up': 'Picked Up',
    'kitchen.no_completed_pickups': 'No completed pickups.',
    'kitchen.cancelled': 'Cancelled',
    'kitchen.no_cancelled_orders': 'No cancelled orders.',
    'kitchen.start_preparing': 'Start Preparing',
    'kitchen.accept': 'Accept',
    'kitchen.cancel_order': 'Cancel Order',
    'kitchen.picked_up_btn': 'Picked Up',

    // Orders
    'orders.title': 'Order Management',
    'orders.live': 'LIVE',
    'orders.subtitle': 'Real-time campus order stream and pickup management.',
    'orders.all_orders': 'All Orders',
    'orders.pending': 'Pending',
    'orders.accepted': 'Accepted',
    'orders.preparing': 'Preparing',
    'orders.ready': 'Ready',
    'orders.completed': 'Completed',
    'orders.cancelled': 'Cancelled',
    'orders.search_placeholder': 'Search orders...',
    'orders.all_roles': 'All Roles',
    'orders.student': 'Student',
    'orders.faculty': 'Faculty',
    'orders.guest': 'Guest',
    'orders.no_orders_yet': 'No orders yet',
    'orders.orders_will_appear': 'Orders from students will appear here in real-time once they place them through the student app.',
    'orders.launch_qr': 'Launch QR Scanner',
    'orders.no_orders_match': 'No orders match your filters',
    'orders.clear_filters': 'Clear filters',
    'orders.order_number': 'Order #',
    'orders.customer': 'Customer',
    'orders.role': 'Role',
    'orders.counter': 'Counter',
    'orders.amount': 'Amount',
    'orders.pickup_time': 'Pickup Time',
    'orders.status': 'Status',
    'orders.actions': 'Actions',
    'orders.view': 'View',
    'orders.accept_order': 'Accept Order',
    'orders.start_preparing': 'Start Preparing',
    'orders.mark_ready': 'Mark Ready',
    'orders.complete_pickup': 'Complete Pickup',
    'orders.cancel_order_btn': 'Cancel Order',

    // Menu
    'menu.title': 'Menu Management',
    'menu.live': 'LIVE',
    'menu.subtitle': 'Manage campus food menu with real-time availability.',

    // Students
    'students.title': 'Student Management',
    'students.subtitle': 'View student profiles, digital campus QR IDs, meal plan status.',
    'students.total_registered': 'Total Registered',
    'students.search_placeholder': 'Search by student name, ID, or email...',
    'students.all_departments': 'All Departments',
    'students.all_blocks': 'All Campus Blocks',
    'students.all_statuses': 'All Statuses',
    'students.profile': 'Profile',
    'students.delete': 'Delete',
    'students.no_students': 'No students found.',

    // Analytics
    'analytics.title': 'Campus Operational Analytics',
    'analytics.subtitle': 'Live order analytics from Supabase.',
    'analytics.total_revenue': 'Total Revenue',
    'analytics.total_orders': 'Total Orders',
    'analytics.data_source': 'Data Source',
    'analytics.live_supabase': 'Live Supabase',
    'analytics.realtime_analytics': 'Real-time analytics',
    'analytics.revenue_by_day': 'Revenue by Day',
    'analytics.top_meals': 'Top Meals',
    'analytics.department_breakdown': 'Department Breakdown',
    'analytics.orders_by_role': 'Orders by Customer Role',
    'analytics.no_data': 'No analytics data available yet.',

    // Reports
    'reports.title': 'Reports & Data Exports',
    'reports.subtitle': 'Generate reports from live Supabase data.',
    'reports.daily': 'Daily',
    'reports.weekly': 'Weekly',
    'reports.monthly': 'Monthly',
    'reports.period_revenue': 'Period Revenue',
    'reports.total_orders': 'Total Orders',
    'reports.total_students': 'Total Students',
    'reports.completed': 'Completed',

    // Campus
    'campus.title': 'Campus & Infrastructure Management',
    'campus.subtitle': 'View institution details, campus blocks, counters, vendors, and staff assignments.',
    'campus.institution_info': 'Institution Information',
    'campus.institution_name': 'Institution Name',
    'campus.institution_code': 'Institution Code',
    'campus.campus_city': 'Campus / City',
    'campus.contact_email': 'Contact Email',
    'campus.phone': 'Phone',
    'campus.joined_date': 'Joined Date',
    'campus.website': 'Website',
    'campus.plan': 'Plan',
    'campus.contact_person': 'Contact Person',
    'campus.campus_blocks': 'Campus Blocks',
    'campus.active_vendors': 'Active Vendors',
    'campus.active_counters': 'Active Counters',
    'campus.staff_members': 'Staff Members',

    // AI Center
    'ai.title': 'FOODEXA AI Intelligence Center',
    'ai.powered_by': 'Powered by Google Gemini',
    'ai.live_summary': 'Live Operational Summary',
    'ai.total_orders': 'Total Orders',
    'ai.revenue': 'Revenue',
    'ai.preparing': 'Preparing',
    'ai.top_item': 'Top Item',
    'ai.menu_items': 'Menu Items',
    'ai.orders_overview': 'Orders Overview',
    'ai.ask_assistant': 'Ask FOODEXA AI Assistant',
    'ai.placeholder': 'Ask AI about sales, prep times, or menu...',

    // Settings
    'settings.title': 'Settings',

    // Common
    'common.live': 'LIVE',
    'common.connected': 'Connected',
    'common.disconnected': 'Disconnected',
    'common.reconnecting': 'Reconnecting...',
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.refresh': 'Refresh',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.no_data': 'No data available.',
    'common.view_kitchen': 'View Kitchen',
    'common.view_all': 'View All',
  },

  hi: {
    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.students': 'छात्र',
    'nav.canteens': 'कैंटीन',
    'nav.kitchen': 'किचन कतार',
    'nav.orders': 'ऑर्डर',
    'nav.menu': 'मेनू',
    'nav.analytics': 'एनालिटिक्स',
    'nav.reports': 'रिपोर्ट',
    'nav.campus': 'कैंपस',
    'nav.staff': 'स्टाफ और भूमिकाएँ',
    'nav.notifications': 'घोषणाएँ',
    'nav.ai_center': 'AI केंद्र',
    'nav.settings': 'सेटिंग्स',

    // Dashboard
    'dashboard.greeting.morning': 'शुभ प्रभात',
    'dashboard.greeting.afternoon': 'शुभ अपराह्न',
    'dashboard.greeting.evening': 'शुभ संध्या',
    'dashboard.todays_orders': 'आज के ऑर्डर',
    'dashboard.todays_revenue': 'आज की आय',
    'dashboard.preparing': 'तैयार हो रहा है',
    'dashboard.ready': 'तैयार',
    'dashboard.completed': 'पूर्ण',
    'dashboard.active_canteens': 'सक्रिय कैंटीन',
    'dashboard.live_operations': 'लाइव ऑपरेशन',
    'dashboard.realtime_pipeline': 'रीयल-टाइम ऑर्डर पाइपलाइन',
    'dashboard.view_kitchen': 'किचन देखें',
    'dashboard.kitchen_queue': 'किचन कतार',
    'dashboard.orders_requiring_attention': 'ध्यान देने योग्य ऑर्डर',
    'dashboard.view_all': 'सभी देखें',
    'dashboard.no_active_orders': 'कोई सक्रिय ऑर्डर नहीं',
    'dashboard.orders_will_appear': 'छात्रों द्वारा ऑर्डर करने पर ऑर्डर यहाँ दिखाई देंगे',
    'dashboard.quick_actions': 'त्वरित क्रियाएँ',
    'dashboard.manage_menu': 'मेनू प्रबंधन',
    'dashboard.add_or_update': 'आइटम जोड़ें या अपडेट करें',
    'dashboard.announcements': 'घोषणाएँ',
    'dashboard.broadcast_to_campus': 'कैंपस में प्रसारित करें',
    'dashboard.scan_pickup': 'पिकअप स्कैन',
    'dashboard.qr_code_scanner': 'QR कोड स्कैनर',
    'dashboard.reports': 'रिपोर्ट',
    'dashboard.export_data': 'डेटा और एनालिटिक्स निर्यात',
    'dashboard.canteens': 'कैंटीन',
    'dashboard.total_orders': 'कुल ऑर्डर',
    'dashboard.active_canteen_count': 'सक्रिय कैंटीन',
    'dashboard.orders_being_prepared': 'ऑर्डर तैयार हो रहे हैं।',

    // Kitchen
    'kitchen.title': 'किचन कतार प्रदर्शन प्रणाली',
    'kitchen.live': 'लाइव',
    'kitchen.subtitle': 'लॉग इन किए गए संस्थान के लिए Supabase रीयलटाइम ऑर्डर।',
    'kitchen.queue': 'कतार',
    'kitchen.incoming_queue': 'आने वाली कतार',
    'kitchen.pending_accepted': 'लंबित / स्वीकृत',
    'kitchen.no_pending_orders': 'कोई लंबित ऑर्डर नहीं।',
    'kitchen.preparing': 'तैयार हो रहा है',
    'kitchen.live_timer': 'लाइव टाइमर',
    'kitchen.no_orders_preparing': 'कोई ऑर्डर तैयार नहीं हो रहा।',
    'kitchen.ready_counter': 'तैयार काउंटर',
    'kitchen.ready': 'तैयार',
    'kitchen.no_orders_ready': 'कोई ऑर्डर तैयार नहीं।',
    'kitchen.completed': 'पूर्ण',
    'kitchen.picked_up': 'उठाया गया',
    'kitchen.no_completed_pickups': 'कोई पूर्ण पिकअप नहीं।',
    'kitchen.cancelled': 'रद्द',
    'kitchen.no_cancelled_orders': 'कोई रद्द ऑर्डर नहीं।',
    'kitchen.start_preparing': 'तैयारी शुरू करें',
    'kitchen.accept': 'स्वीकारें',
    'kitchen.cancel_order': 'ऑर्डर रद्द करें',
    'kitchen.picked_up_btn': 'उठाया गया',

    // Orders
    'orders.title': 'ऑर्डर प्रबंधन',
    'orders.live': 'लाइव',
    'orders.subtitle': 'रीयल-टाइम कैंपस ऑर्डर स्ट्रीम और पिकअप प्रबंधन।',
    'orders.all_orders': 'सभी ऑर्डर',
    'orders.pending': 'लंबित',
    'orders.accepted': 'स्वीकृत',
    'orders.preparing': 'तैयार हो रहा है',
    'orders.ready': 'तैयार',
    'orders.completed': 'पूर्ण',
    'orders.cancelled': 'रद्द',
    'orders.search_placeholder': 'ऑर्डर खोजें...',
    'orders.all_roles': 'सभी भूमिकाएँ',
    'orders.student': 'छात्र',
    'orders.faculty': 'संकाय',
    'orders.guest': 'अतिथि',
    'orders.no_orders_yet': 'अभी तक कोई ऑर्डर नहीं',
    'orders.orders_will_appear': 'छात्र ऐप के माध्यम से ऑर्डर करने पर छात्रों के ऑर्डर यहाँ रीयल-टाइम में दिखाई देंगे।',
    'orders.launch_qr': 'QR स्कैनर लॉन्च करें',
    'orders.no_orders_match': 'कोई ऑर्डर आपके फ़िल्टर से मेल नहीं खाता',
    'orders.clear_filters': 'फ़िल्टर साफ़ करें',
    'orders.order_number': 'ऑर्डर #',
    'orders.customer': 'ग्राहक',
    'orders.role': 'भूमिका',
    'orders.counter': 'काउंटर',
    'orders.amount': 'राशि',
    'orders.pickup_time': 'पिकअप समय',
    'orders.status': 'स्थिति',
    'orders.actions': 'क्रियाएँ',
    'orders.view': 'देखें',
    'orders.accept_order': 'ऑर्डर स्वीकारें',
    'orders.start_preparing': 'तैयारी शुरू करें',
    'orders.mark_ready': 'तैयार चिन्हित करें',
    'orders.complete_pickup': 'पिकअप पूर्ण करें',
    'orders.cancel_order_btn': 'ऑर्डर रद्द करें',

    // Menu
    'menu.title': 'मेनू प्रबंधन',
    'menu.live': 'लाइव',
    'menu.subtitle': 'रीयल-टाइम उपलब्धता के साथ कैंपस भोजन मेनू प्रबंधित करें।',

    // Students
    'students.title': 'छात्र प्रबंधन',
    'students.subtitle': 'छात्र प्रोफ़ाइल, डिजिटल कैंपस QR ID, भोजन योजना स्थिति देखें।',
    'students.total_registered': 'कुल पंजीकृत',
    'students.search_placeholder': 'छात्र का नाम, ID या ईमेल से खोजें...',
    'students.all_departments': 'सभी विभाग',
    'students.all_blocks': 'सभी कैंपस ब्लॉक',
    'students.all_statuses': 'सभी स्थितियाँ',
    'students.profile': 'प्रोफ़ाइल',
    'students.delete': 'हटाएँ',
    'students.no_students': 'कोई छात्र नहीं मिला।',

    // Analytics
    'analytics.title': 'कैंपस संचालन एनालिटिक्स',
    'analytics.subtitle': 'Supabase से लाइव ऑर्डर एनालिटिक्स।',
    'analytics.total_revenue': 'कुल आय',
    'analytics.total_orders': 'कुल ऑर्डर',
    'analytics.data_source': 'डेटा स्रोत',
    'analytics.live_supabase': 'लाइव Supabase',
    'analytics.realtime_analytics': 'रीयल-टाइम एनालिटिक्स',
    'analytics.revenue_by_day': 'दिन के अनुसार आय',
    'analytics.top_meals': 'लोकप्रिय भोजन',
    'analytics.department_breakdown': 'विभाग विवरण',
    'analytics.orders_by_role': 'ग्राहक भूमिका के अनुसार ऑर्डर',
    'analytics.no_data': 'अभी तक कोई एनालिटिक्स डेटा उपलब्ध नहीं है।',

    // Reports
    'reports.title': 'रिपोर्ट और डेटा निर्यात',
    'reports.subtitle': 'लाइव Supabase डेटा से रिपोर्ट बनाएँ।',
    'reports.daily': 'दैनिक',
    'reports.weekly': 'साप्ताहिक',
    'reports.monthly': 'मासिक',
    'reports.period_revenue': 'अवधि की आय',
    'reports.total_orders': 'कुल ऑर्डर',
    'reports.total_students': 'कुल छात्र',
    'reports.completed': 'पूर्ण',

    // Campus
    'campus.title': 'कैंपस और अवसंरचना प्रबंधन',
    'campus.subtitle': 'संस्थान विवरण, कैंपस ब्लॉक, काउंटर, विक्रेता और स्टाफ असाइनमेंट देखें।',
    'campus.institution_info': 'संस्थान जानकारी',
    'campus.institution_name': 'संस्थान का नाम',
    'campus.institution_code': 'संस्थान कोड',
    'campus.campus_city': 'कैंपस / शहर',
    'campus.contact_email': 'संपर्क ईमेल',
    'campus.phone': 'फ़ोन',
    'campus.joined_date': 'शामिल होने की तारीख',
    'campus.website': 'वेबसाइट',
    'campus.plan': 'योजना',
    'campus.contact_person': 'संपर्क व्यक्ति',
    'campus.campus_blocks': 'कैंपस ब्लॉक',
    'campus.active_vendors': 'सक्रिय विक्रेता',
    'campus.active_counters': 'सक्रिय काउंटर',
    'campus.staff_members': 'स्टाफ सदस्य',

    // AI Center
    'ai.title': 'FOODEXA AI इंटेलिजेंस सेंटर',
    'ai.powered_by': 'Google Gemini द्वारा संचालित',
    'ai.live_summary': 'लाइव संचालन सारांश',
    'ai.total_orders': 'कुल ऑर्डर',
    'ai.revenue': 'आय',
    'ai.preparing': 'तैयार हो रहा है',
    'ai.top_item': 'लोकप्रिय आइटम',
    'ai.menu_items': 'मेनू आइटम',
    'ai.orders_overview': 'ऑर्डर अवलोकन',
    'ai.ask_assistant': 'FOODEXA AI सहायक से पूछें',
    'ai.placeholder': 'AI से बिक्री, तैयारी समय या मेनू के बारे में पूछें...',

    // Settings
    'settings.title': 'सेटिंग्स',

    // Common
    'common.live': 'लाइव',
    'common.connected': 'जुड़ा हुआ',
    'common.disconnected': 'डिस्कनेक्ट',
    'common.reconnecting': 'पुनः जुड़ रहा है...',
    'common.loading': 'लोड हो रहा है...',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएँ',
    'common.edit': 'संपादित करें',
    'common.add': 'जोड़ें',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर',
    'common.export': 'निर्यात',
    'common.refresh': 'रीफ्रेश',
    'common.close': 'बंद करें',
    'common.confirm': 'पुष्टि करें',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.previous': 'पिछला',
    'common.no_data': 'कोई डेटा उपलब्ध नहीं।',
    'common.view_kitchen': 'किचन देखें',
    'common.view_all': 'सभी देखें',
  },

  kn: {
    // Navigation
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.students': 'ವಿದ್ಯಾರ್ಥಿಗಳು',
    'nav.canteens': 'ಕ್ಯಾಂಟೀನ್‌ಗಳು',
    'nav.kitchen': 'ಅಡುಗೆ ಸಾಲು',
    'nav.orders': 'ಆರ್ಡರ್‌ಗಳು',
    'nav.menu': 'ಮೆನು',
    'nav.analytics': 'ವಿಶ್ಲೇಷಣೆ',
    'nav.reports': 'ವರದಿಗಳು',
    'nav.campus': 'ಕ್ಯಾಂಪಸ್',
    'nav.staff': 'ಸಿಬ್ಬಂದಿ ಮತ್ತು ಪಾತ್ರಗಳು',
    'nav.notifications': 'ಘೋಷಣೆಗಳು',
    'nav.ai_center': 'AI ಕೇಂದ್ರ',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',

    // Dashboard
    'dashboard.greeting.morning': 'ಶುಭ ಬೆಳಗ್ಗೆ',
    'dashboard.greeting.afternoon': 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
    'dashboard.greeting.evening': 'ಶುಭ ಸಂಜೆ',
    'dashboard.todays_orders': 'ಇಂದಿನ ಆರ್ಡರ್‌ಗಳು',
    'dashboard.todays_revenue': 'ಇಂದಿನ ಆದಾಯ',
    'dashboard.preparing': 'ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ',
    'dashboard.ready': 'ಸಿದ್ಧ',
    'dashboard.completed': 'ಪೂರ್ಣ',
    'dashboard.active_canteens': 'ಸಕ್ರಿಯ ಕ್ಯಾಂಟೀನ್‌ಗಳು',
    'dashboard.live_operations': 'ಲೈವ್ ಕಾರ್ಯಾಚರಣೆಗಳು',
    'dashboard.realtime_pipeline': 'ರಿಯಲ್-ಟೈಮ್ ಆರ್ಡರ್ ಪೈಪ್‌ಲೈನ್',
    'dashboard.view_kitchen': 'ಅಡುಗೆ ನೋಡಿ',
    'dashboard.kitchen_queue': 'ಅಡುಗೆ ಸಾಲು',
    'dashboard.orders_requiring_attention': 'ಗಮನ ಬೇಕಾದ ಆರ್ಡರ್‌ಗಳು',
    'dashboard.view_all': 'ಎಲ್ಲಾ ನೋಡಿ',
    'dashboard.no_active_orders': 'ಯಾವುದೇ ಸಕ್ರಿಯ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ',
    'dashboard.orders_will_appear': 'ವಿದ್ಯಾರ್ಥಿಗಳು ಆರ್ಡರ್ ಮಾಡಿದಾಗ ಆರ್ಡರ್‌ಗಳು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ',
    'dashboard.quick_actions': 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    'dashboard.manage_menu': 'ಮೆನು ನಿರ್ವಹಣೆ',
    'dashboard.add_or_update': 'ಐಟಂಗಳನ್ನು ಸೇರಿಸಿ ಅಥವಾ ನವೀಕರಿಸಿ',
    'dashboard.announcements': 'ಘೋಷಣೆಗಳು',
    'dashboard.broadcast_to_campus': 'ಕ್ಯಾಂಪಸ್‌ಗೆ ಪ್ರಸಾರಿಸಿ',
    'dashboard.scan_pickup': 'ಪಿಕಪ್ ಸ್ಕ್ಯಾನ್',
    'dashboard.qr_code_scanner': 'QR ಕೋಡ್ ಸ್ಕ್ಯಾನರ್',
    'dashboard.reports': 'ವರದಿಗಳು',
    'dashboard.export_data': 'ಡೇಟಾ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ ರಫ್ತು',
    'dashboard.canteens': 'ಕ್ಯಾಂಟೀನ್‌ಗಳು',
    'dashboard.total_orders': 'ಒಟ್ಟು ಆರ್ಡರ್‌ಗಳು',
    'dashboard.active_canteen_count': 'ಸಕ್ರಿಯ ಕ್ಯಾಂಟೀನ್‌ಗಳು',
    'dashboard.orders_being_prepared': 'ಆರ್ಡರ್‌ಗಳು ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ.',

    // Kitchen
    'kitchen.title': 'ಅಡುಗೆ ಸಾಲು ಪ್ರದರ್ಶನ ವ್ಯವಸ್ಥೆ',
    'kitchen.live': 'ಲೈವ್',
    'kitchen.subtitle': 'ಲಾಗ್ ಇನ್ ಮಾಡಿದ ಸಂಸ್ಥೆಗೆ Supabase ರಿಯಲ್‌ಟೈಮ್ ಆರ್ಡರ್‌ಗಳು।',
    'kitchen.queue': 'ಸಾಲು',
    'kitchen.incoming_queue': 'ಬರುತ್ತಿರುವ ಸಾಲು',
    'kitchen.pending_accepted': 'ಬಾಕಿ / ಸ್ವೀಕೃತ',
    'kitchen.no_pending_orders': 'ಯಾವುದೇ ಬಾಕಿ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ।',
    'kitchen.preparing': 'ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ',
    'kitchen.live_timer': 'ಲೈವ್ ಟೈಮರ್',
    'kitchen.no_orders_preparing': 'ಯಾವುದೇ ಆರ್ಡರ್ ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿಲ್ಲ।',
    'kitchen.ready_counter': 'ಸಿದ್ಧ ಕೌಂಟರ್',
    'kitchen.ready': 'ಸಿದ್ಧ',
    'kitchen.no_orders_ready': 'ಯಾವುದೇ ಆರ್ಡರ್ ಸಿದ್ಧವಾಗಿಲ್ಲ।',
    'kitchen.completed': 'ಪೂರ್ಣ',
    'kitchen.picked_up': 'ತೆಗೆದುಕೊಳ್ಳಲಾಗಿದೆ',
    'kitchen.no_completed_pickups': 'ಯಾವುದೇ ಪೂರ್ಣ ಪಿಕಪ್‌ಗಳಿಲ್ಲ।',
    'kitchen.cancelled': 'ರದ್ದು',
    'kitchen.no_cancelled_orders': 'ಯಾವುದೇ ರದ್ದು ಆರ್ಡರ್‌ಗಳಿಲ್ಲ।',
    'kitchen.start_preparing': 'ಸಿದ್ಧತೆ ಪ್ರಾರಂಭಿಸಿ',
    'kitchen.accept': 'ಸ್ವೀಕರಿಸಿ',
    'kitchen.cancel_order': 'ಆರ್ಡರ್ ರದ್ದುಮಾಡಿ',
    'kitchen.picked_up_btn': 'ತೆಗೆದುಕೊಳ್ಳಲಾಗಿದೆ',

    // Orders
    'orders.title': 'ಆರ್ಡರ್ ನಿರ್ವಹಣೆ',
    'orders.live': 'ಲೈವ್',
    'orders.subtitle': 'ರಿಯಲ್-ಟೈಮ್ ಕ್ಯಾಂಪಸ್ ಆರ್ಡರ್ ಸ್ಟ್ರೀಮ್ ಮತ್ತು ಪಿಕಪ್ ನಿರ್ವಹಣೆ।',
    'orders.all_orders': 'ಎಲ್ಲಾ ಆರ್ಡರ್‌ಗಳು',
    'orders.pending': 'ಬಾಕಿ',
    'orders.accepted': 'ಸ್ವೀಕೃತ',
    'orders.preparing': 'ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ',
    'orders.ready': 'ಸಿದ್ಧ',
    'orders.completed': 'ಪೂರ್ಣ',
    'orders.cancelled': 'ರದ್ದು',
    'orders.search_placeholder': 'ಆರ್ಡರ್‌ಗಳನ್ನು ಹುಡುಕಿ...',
    'orders.all_roles': 'ಎಲ್ಲಾ ಪಾತ್ರಗಳು',
    'orders.student': 'ವಿದ್ಯಾರ್ಥಿ',
    'orders.faculty': 'ಬೋಧಕ',
    'orders.guest': 'ಅತಿಥಿ',
    'orders.no_orders_yet': 'ಇನ್ನೂ ಯಾವುದೇ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ',
    'orders.orders_will_appear': 'ವಿದ್ಯಾರ್ಥಿ ಅಪ್ಲಿಕೇಶನ್ ಮೂಲಕ ಆರ್ಡರ್ ಮಾಡಿದಾಗ ವಿದ್ಯಾರ್ಥಿಗಳ ಆರ್ಡರ್‌ಗಳು ಇಲ್ಲಿ ರಿಯಲ್-ಟೈಮ್‌ನಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ।',
    'orders.launch_qr': 'QR ಸ್ಕ್ಯಾನರ್ ಪ್ರಾರಂಭಿಸಿ',
    'orders.no_orders_match': 'ಯಾವುದೇ ಆರ್ಡರ್ ನಿಮ್ಮ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ',
    'orders.clear_filters': 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ',
    'orders.order_number': 'ಆರ್ಡರ್ #',
    'orders.customer': 'ಗ್ರಾಹಕ',
    'orders.role': 'ಪಾತ್ರ',
    'orders.counter': 'ಕೌಂಟರ್',
    'orders.amount': 'ಮೊತ್ತ',
    'orders.pickup_time': 'ಪಿಕಪ್ ಸಮಯ',
    'orders.status': 'ಸ್ಥಿತಿ',
    'orders.actions': 'ಕ್ರಿಯೆಗಳು',
    'orders.view': 'ನೋಡಿ',
    'orders.accept_order': 'ಆರ್ಡರ್ ಸ್ವೀಕರಿಸಿ',
    'orders.start_preparing': 'ಸಿದ್ಧತೆ ಪ್ರಾರಂಭಿಸಿ',
    'orders.mark_ready': 'ಸಿದ್ಧ ಎಂದು ಗುರುತಿಸಿ',
    'orders.complete_pickup': 'ಪಿಕಪ್ ಪೂರ್ಣಗೊಳಿಸಿ',
    'orders.cancel_order_btn': 'ಆರ್ಡರ್ ರದ್ದುಮಾಡಿ',

    // Menu
    'menu.title': 'ಮೆನು ನಿರ್ವಹಣೆ',
    'menu.live': 'ಲೈವ್',
    'menu.subtitle': 'ರಿಯಲ್-ಟೈಮ್ ಲಭ್ಯತೆಯೊಂದಿಗೆ ಕ್ಯಾಂಪಸ್ ಆಹಾರ ಮೆನು ನಿರ್ವಹಿಸಿ।',

    // Students
    'students.title': 'ವಿದ್ಯಾರ್ಥಿ ನಿರ್ವಹಣೆ',
    'students.subtitle': 'ವಿದ್ಯಾರ್ಥಿ ಪ್ರೊಫೈಲ್‌ಗಳು, ಡಿಜಿಟಲ್ ಕ್ಯಾಂಪಸ್ QR ID, ಊಟ ಯೋಜನೆ ಸ್ಥಿತಿ ನೋಡಿ।',
    'students.total_registered': 'ಒಟ್ಟು ನೋಂದಾಯಿತ',
    'students.search_placeholder': 'ವಿದ್ಯಾರ್ಥಿ ಹೆಸರು, ID ಅಥವಾ ಇಮೇಲ್ ಮೂಲಕ ಹುಡುಕಿ...',
    'students.all_departments': 'ಎಲ್ಲಾ ಇಲಾಖೆಗಳು',
    'students.all_blocks': 'ಎಲ್ಲಾ ಕ್ಯಾಂಪಸ್ ಬ್ಲಾಕ್‌ಗಳು',
    'students.all_statuses': 'ಎಲ್ಲಾ ಸ್ಥಿತಿಗಳು',
    'students.profile': 'ಪ್ರೊಫೈಲ್',
    'students.delete': 'ಅಳಿಸಿ',
    'students.no_students': 'ಯಾವುದೇ ವಿದ್ಯಾರ್ಥಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ।',

    // Analytics
    'analytics.title': 'ಕ್ಯಾಂಪಸ್ ಕಾರ್ಯಾಚರಣೆ ವಿಶ್ಲೇಷಣೆ',
    'analytics.subtitle': 'Supabase ನಿಂದ ಲೈವ್ ಆರ್ಡರ್ ವಿಶ್ಲೇಷಣೆ।',
    'analytics.total_revenue': 'ಒಟ್ಟು ಆದಾಯ',
    'analytics.total_orders': 'ಒಟ್ಟು ಆರ್ಡರ್‌ಗಳು',
    'analytics.data_source': 'ಡೇಟಾ ಮೂಲ',
    'analytics.live_supabase': 'ಲೈವ್ Supabase',
    'analytics.realtime_analytics': 'ರಿಯಲ್-ಟೈಮ್ ವಿಶ್ಲೇಷಣೆ',
    'analytics.revenue_by_day': 'ದಿನದ ಆದಾಯ',
    'analytics.top_meals': 'ಜನಪ್ರಿಯ ಊಟ',
    'analytics.department_breakdown': 'ಇಲಾಖೆ ವಿವರ',
    'analytics.orders_by_role': 'ಗ್ರಾಹಕ ಪಾತ್ರದ ಆರ್ಡರ್‌ಗಳು',
    'analytics.no_data': 'ಇನ್ನೂ ಯಾವುದೇ ವಿಶ್ಲೇಷಣೆ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ।',

    // Reports
    'reports.title': 'ವರದಿಗಳು ಮತ್ತು ಡೇಟಾ ರಫ್ತುಗಳು',
    'reports.subtitle': 'ಲೈವ್ Supabase ಡೇಟಾದಿಂದ ವರದಿಗಳನ್ನು ರಚಿಸಿ।',
    'reports.daily': 'ದೈನಂದಿನ',
    'reports.weekly': 'ಸಾಪ್ತಾಹಿಕ',
    'reports.monthly': 'ಮಾಸಿಕ',
    'reports.period_revenue': 'ಅವಧಿಯ ಆದಾಯ',
    'reports.total_orders': 'ಒಟ್ಟು ಆರ್ಡರ್‌ಗಳು',
    'reports.total_students': 'ಒಟ್ಟು ವಿದ್ಯಾರ್ಥಿಗಳು',
    'reports.completed': 'ಪೂರ್ಣ',

    // Campus
    'campus.title': 'ಕ್ಯಾಂಪಸ್ ಮತ್ತು ಮೂಲಸೌಕರ್ಯ ನಿರ್ವಹಣೆ',
    'campus.subtitle': 'ಸಂಸ್ಥೆ ವಿವರಗಳು, ಕ್ಯಾಂಪಸ್ ಬ್ಲಾಕ್‌ಗಳು, ಕೌಂಟರ್‌ಗಳು, ವ್ಯಾಪಾರಿಗಳು ಮತ್ತು ಸಿಬ್ಬಂದಿ ನಿಯೋಜನೆಗಳನ್ನು ನೋಡಿ।',
    'campus.institution_info': 'ಸಂಸ್ಥೆ ಮಾಹಿತಿ',
    'campus.institution_name': 'ಸಂಸ್ಥೆಯ ಹೆಸರು',
    'campus.institution_code': 'ಸಂಸ್ಥೆ ಕೋಡ್',
    'campus.campus_city': 'ಕ್ಯಾಂಪಸ್ / ನಗರ',
    'campus.contact_email': 'ಸಂಪರ್ಕ ಇಮೇಲ್',
    'campus.phone': 'ಫೋನ್',
    'campus.joined_date': 'ಸೇರಿದ ದಿನಾಂಕ',
    'campus.website': 'ವೆಬ್‌ಸೈಟ್',
    'campus.plan': 'ಯೋಜನೆ',
    'campus.contact_person': 'ಸಂಪರ್ಕ ವ್ಯಕ್ತಿ',
    'campus.campus_blocks': 'ಕ್ಯಾಂಪಸ್ ಬ್ಲಾಕ್‌ಗಳು',
    'campus.active_vendors': 'ಸಕ್ರಿಯ ವ್ಯಾಪಾರಿಗಳು',
    'campus.active_counters': 'ಸಕ್ರಿಯ ಕೌಂಟರ್‌ಗಳು',
    'campus.staff_members': 'ಸಿಬ್ಬಂದಿ ಸದಸ್ಯರು',

    // AI Center
    'ai.title': 'FOODEXA AI ಇಂಟೆಲಿಜೆನ್ಸ್ ಸೆಂಟರ್',
    'ai.powered_by': 'Google Gemini ನಿಂದ ಚಾಲಿತ',
    'ai.live_summary': 'ಲೈವ್ ಕಾರ್ಯಾಚರಣೆ ಸಾರಾಂಶ',
    'ai.total_orders': 'ಒಟ್ಟು ಆರ್ಡರ್‌ಗಳು',
    'ai.revenue': 'ಆದಾಯ',
    'ai.preparing': 'ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ',
    'ai.top_item': 'ಜನಪ್ರಿಯ ಐಟಂ',
    'ai.menu_items': 'ಮೆನು ಐಟಂಗಳು',
    'ai.orders_overview': 'ಆರ್ಡರ್ ಅವಲೋಕನ',
    'ai.ask_assistant': 'FOODEXA AI ಸಹಾಯಕರನ್ನು ಕೇಳಿ',
    'ai.placeholder': 'AI ನಲ್ಲಿ ಮಾರಾಟ, ಸಿದ್ಧತೆ ಸಮಯ ಅಥವಾ ಮೆನು ಬಗ್ಗೆ ಕೇಳಿ...',

    // Settings
    'settings.title': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',

    // Common
    'common.live': 'ಲೈವ್',
    'common.connected': 'ಸಂಪರ್ಕಿತ',
    'common.disconnected': 'ಸಂಪರ್ಕ ಕಡಿತ',
    'common.reconnecting': 'ಮರು ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...',
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'common.save': 'ಉಳಿಸಿ',
    'common.cancel': 'ರದ್ದುಮಾಡಿ',
    'common.delete': 'ಅಳಿಸಿ',
    'common.edit': 'ಸಂಪಾದಿಸಿ',
    'common.add': 'ಸೇರಿಸಿ',
    'common.search': 'ಹುಡುಕಿ',
    'common.filter': 'ಫಿಲ್ಟರ್',
    'common.export': 'ರಫ್ತು',
    'common.refresh': 'ರಿಫ್ರೆಶ್',
    'common.close': 'ಮುಚ್ಚಿ',
    'common.confirm': 'ದೃಢೀಕರಿಸಿ',
    'common.back': 'ಹಿಂದೆ',
    'common.next': 'ಮುಂದೆ',
    'common.previous': 'ಹಿಂದಿನ',
    'common.no_data': 'ಯಾವುದೇ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ।',
    'common.view_kitchen': 'ಅಡುಗೆ ನೋಡಿ',
    'common.view_all': 'ಎಲ್ಲಾ ನೋಡಿ',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('foodexa_language');
    if (saved === 'en' || saved === 'hi' || saved === 'kn') {
      return saved;
    }
    return 'en';
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('foodexa_language', lang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
